agents:
  image: "docker.elastic.co/ci-agent-images/eck-region/go-builder-buildkite-agent:1.19-02"
  cpu: "4"
  memory: "4G"

env:
  DOCKER_IMAGE: "docker.elastic.co/cloud-ci/k8s-arch/elasticsearch-k8s-metrics-adapter"
  DOCKER_IMAGE_TAG: "git-${BUILDKITE_COMMIT:0:12}"

steps:
  - label: ":go: Run unit tests"
    command: "make test"
    key: "tests"
    artifact_paths:
      - "coverage.out"

  - label: ":sonarqube: Static Code Analysis"
    env:
      VAULT_SONAR_TOKEN_PATH: "kv/ci-shared/serverless/shared-analysis-token"
    agents:
      image: "docker.elastic.co/cloud-ci/sonarqube/buildkite-scanner:latest"
    command:
      - "buildkite-agent artifact download coverage.out ."
      - "/scan-source-code.sh"
    soft_fail: true
    depends_on: "tests"

  # Need go 1.20 in the serverless-docker-builder to enable this 
  #- label: ":go: Build"
  #  command: "make all"

  # multiarch dockerx build
  - group: ":docker: Build Container Images"
    steps:
      - label: ":docker: :seedling: Trigger Image Creation"
        command: "make -C /agent generate-docker-images"
        agents:
          image: "docker.elastic.co/ci-agent-images/serverless-docker-builder:0.0.4"